"""add token usage columns to chat_messages

Revision ID: 296f1aa6481b
Revises: 003
Create Date: 2026-04-08 16:16:03.273599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296f1aa6481b'
down_revision: Union[str, Sequence[str], None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('output_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'output_tokens')
    op.drop_column('chat_messages', 'input_tokens')
    # ### end Alembic commands ###
